# -*- coding: utf-8 -*-
"""CHATBOT_I.A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19LGpKsn-nAQugw4BjTGPnIFAsUQdwI8K
"""

!pip install chatterbot2

from chatterbot import trainers
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer
# Uncomment the following lines to enable verbose logging
import logging
logging.basicConfig(level=logging.INFO)

bot = ChatBot(
    'Blinky',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
        logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter'

    ],
    database_uri=None

)
while True:
    try:
        bot_input = bot.get_response(input())
        print(bot_input)

    except(KeyboardInterrupt, EOFError, SystemExit):
        break

bot.train([
    'Hello',
    'Hi!',
    '¿What´s you name?',
    'My name is Blinky',
    'Hi Blink',
])



